[package]
name = "connect4"
version = "0.1.0"
authors = ["Name <@>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
